version: '3.8'

services:
  # Order Service
  order-service:
    image: order-service:${VERSION:-latest}
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=${ORDER_DB_URL}
      - SPRING_DATASOURCE_USERNAME=${ORDER_DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${ORDER_DB_PASSWORD}
      - SPRING_RABBITMQ_HOST=${RABBITMQ_HOST}
      - SPRING_RABBITMQ_PORT=${RABBITMQ_PORT}
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - JAVA_OPTS=-Xmx512m -Xms256m
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 768M
        reservations:
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    networks:
      - microservices-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Payment Service
  payment-service:
    image: payment-service:${VERSION:-latest}
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=${PAYMENT_DB_URL}
      - SPRING_DATASOURCE_USERNAME=${PAYMENT_DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${PAYMENT_DB_PASSWORD}
      - SPRING_RABBITMQ_HOST=${RABBITMQ_HOST}
      - SPRING_RABBITMQ_PORT=${RABBITMQ_PORT}
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - JAVA_OPTS=-Xmx512m -Xms256m
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 768M
        reservations:
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    networks:
      - microservices-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  microservices-network:
    external: true